########################## Collectbeat Configuration ###########################

# This file is a full configuration example documenting all non-deprecated
# options in comments. For a shorter configuration example, that contains only
# the most common options, please see metricbeat.yml in the same directory.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/metricbeat/index.html

#==========================  Modules configuration ============================
collectbeat.modules:

#-------------------------------- beats Module -------------------------------
- module: beats
  metricsets: ["generatorbeat"]
  enabled: true
  period: 1s
  hosts: ["localhost"]



